### ISSUE TITLE
Checkbox design is confusing

### ISSUE THREAD

**Issue by itsmohmans** [mbaraa/dankmuzikk#54]
A checkbox without a tick icon makes it confusing on which state is checked.
![image](https://github.com/mbaraa/dankmuzikk/assets/55551984/1898782b-108d-47b5-a4ef-cd0dc354b59e)
![image](https://github.com/mbaraa/dankmuzikk/assets/55551984/8ac05804-d8c5-492c-b998-9842562f1c94)

**Comment by mbaraa** [comment]
A tick sign is actually a good addition, since it's the default web way (the lord's way)
