### ISSUE TITLE
Songs not loading properly on Safari (iOS)

### ISSUE THREAD

**Issue by AbdallahSaleh03** [mbaraa/dankmuzikk#80]
**Describe the bug**
**** I was using Safari on my iphone, and as I was switching between songs; I noticed that the time bar doesnt reset after I click the icon of the new song, and the loaded song doesn't actually play. After the loading bar is done and disappears the song fixates on the point where the previous song was at. *****

**To Reproduce**
1. Go to 'song x'
2. play it for y seconds 
3. click on song z 

**Expected behavior**
when done playing song x and playing song z, song z should reset the time bar and start from time 0, not from time y

**Smartphone (please complete the following information):**
 - Device: iPhone xs max
 - OS: iOS 17.5.1
 - Browser safari
 - Version 17.5

**Comment by mbaraa** [comment]
Thanks @AbdallahSaleh03, I will look into it as soon as I can!

**Comment by mbaraa** [comment]
@AbdallahSaleh03 this issue was "fixed" in the last [patch](https://github.com/mbaraa/dankmuzikk/pull/88), if you face any issues like it again, don't hesitate to report it again :)

although you might need to click on new songs twice :(
